window.meanings = {
  "chicken": {
    "arabic": "دجاج",
    "english": "chicken",
    "japanese": "チキン",
    "spanish": "pollo",
    "chinese": "鸡",
    "english-arabic": "dijaj",
    "english-chinese": "Jī",
    "arabic-english": "شكن"
  },
  "cow": {
    "arabic": "بقرة",
    "chinese": "牛",
    "english": "cow",
    "japanese": "牛",
    "spanish": "vaca",
    "english-arabic": "baqara",
    "english-japanese": "ushi",
    "english-chinese": "Niú",
    "arabic-english": "كاو"
  },
  "sheep": {
    "arabic": "غنم",
    "english": "sheep",
    "japanese": "羊",
    "spanish": "oveja",
    "chinese": "羊",
    "english-arabic": "ghanem",
    "english-japanese": "hitsuji",
    "english-chinese": "Yáng",
    "arabic-english": "شيپ"
  },
  "goat": {
    "arabic": "ماعز",
    "english": "goat",
    "japanese": "ヤギ",
    "chinese": "山羊",
    "spanish": "cabra",
    "english-arabic": "m3z",
    "english-chinese": "Shānyáng",
    "english-japanese": "yagi",
    "arabic-english": "جوت"
  },
  "pig": {
    "arabic": "خنزير",
    "chinese": "猪",
    "english": "pig",
    "japanese": "豚",
    "spanish": "cerdo",
    "english-arabic": "khnzeer",
    "english-chinese": "Zhū",
    "english-japanese": "buta",
    "arabic-english": "پج"
  },
  "fish": {
    "arabic": "سمك",
    "chinese": "鱼",
    "english": "fish",
    "japanese": "魚",
    "spanish": "pescado",
    "english-arabic": "samak",
    "english-chinese": "Yú",
    "english-japanese": "sakana",
    "arabic-english": "فش"
  },
  "rabbit": {
    "arabic": "أرنب",
    "chinese": "兔子",
    "english": "rabbit",
    "japanese": "ウサギ",
    "spanish": "conejo",
    "english-arabic": "arnab",
    "english-chinese": "Tùzǐ",
    "english-japanese": "usagi",
    "arabic-english": "رابت"
  },
  "crab": {
    "arabic": "سلطعون",
    "chinese": "螃蟹",
    "english": "crab",
    "japanese": "カニ",
    "spanish": "cangrejo",
    "english-arabic": "salat3oon",
    "english-chinese": "Pángxiè",
    "english-japanese": "kani",
    "arabic-english": "كراب"
  },
  "deer": {
    "arabic": "غزال",
    "chinese": "鹿",
    "english": "deer",
    "japanese": "鹿",
    "spanish": "ciervo",
    "english-arabic": "ghazal",
    "english-chinese": "Lù",
    "english-japanese": "shika",
    "arabic-english": "دير"
  },
  "0": {
    "arabic": "٠",
    "chinese": "零",
    "english": "0",
    "japanese": "〇",
    "spanish": "0",
    "english-arabic": "sifr",
    "english-chinese": "Líng",
    "arabic-english": "زيرو"
  },
  "1": {
    "arabic": "١",
    "chinese": "一",
    "english": "1",
    "japanese": "一",
    "spanish": "1",
    "english-arabic": "wahid",
    "english-chinese": "Yī",
    "english-japanese": "ichi",
    "arabic-english": "ون"
  },
  "2": {
    "arabic": "٢",
    "chinese": "二",
    "english": "2",
    "japanese": "二",
    "spanish": "2",
    "english-arabic": "ithnayn",
    "english-chinese": "Èr",
    "english-japanese": "ni",
    "arabic-english": "تو"
  },
  "3": {
    "arabic": "٣",
    "chinese": "三",
    "english": "3",
    "japanese": "三",
    "spanish": "3",
    "english-arabic": "thalatha",
    "english-chinese": "san",
    "english-japanese": "san",
    "arabic-english": "ثري"
  },
  "4": {
    "arabic": "٤",
    "chinese": "四",
    "english": "4",
    "japanese": "四",
    "spanish": "4",
    "english-arabic": "arba3a",
    "english-chinese": "Sì",
    "english-japanese": "shi / yon",
    "arabic-english": "فور"
  },
  "5": {
    "arabic": "٥",
    "chinese": "五",
    "english": "5",
    "japanese": "五",
    "spanish": "5",
    "english-arabic": "khamsa",
    "english-chinese": "Wǔ",
    "english-japanese": "go",
    "arabic-english": "فيڤ"
  },
  "6": {
    "arabic": "٦",
    "chinese": "六",
    "english": "6",
    "japanese": "六",
    "spanish": "6",
    "english-arabic": "sit'ih",
    "english-chinese": "Liù",
    "english-japanese": "roku",
    "arabic-english": "سكس"
  },
  "7": {
    "arabic": "٧",
    "chinese": "七",
    "english": "7",
    "japanese": "七",
    "spanish": "7",
    "english-arabic": "sab3ah",
    "english-chinese": "Qī",
    "english-japanese": "shichi",
    "arabic-english": "سڤن"
  },
  "8": {
    "arabic": "٨",
    "chinese": "八",
    "english": "8",
    "japanese": "八",
    "spanish": "8",
    "english-arabic": "thamanyih",
    "english-chinese": "Bā",
    "english-japanese": "hachi",
    "arabic-english": "ايت"
  },
  "9": {
    "arabic": "٩",
    "chinese": "九",
    "english": "9",
    "japanese": "九",
    "spanish": "9",
    "english-arabic": "tis3ih",
    "english-chinese": "Jiǔ",
    "english-japanese": "kyu",
    "arabic-english": "ناين"
  },
  "red": {
    "arabic": "أحمر",
    "chinese": "红",
    "english": "red",
    "japanese": "赤",
    "spanish": "rojo",
    "english-arabic": "ahmar",
    "english-chinese": "Hóng",
    "english-japanese": "aka",
    "arabic-english": "رد"
  },
  "orange": {
    "arabic": "برتقالي",
    "chinese": "橙子",
    "japanese": "オレンジ",
    "english": "orange",
    "spanish": "naranja",
    "english-arabic": "burtuqali",
    "english-chinese": "Chéngzi",
    "arabic-english": "اورنج"
  },
  "yellow": {
    "arabic": "أصفر",
    "chinese": "黄色",
    "english": "yellow",
    "japanese": "黄",
    "spanish": "amarillo",
    "english-arabic": "asfar",
    "english-chinese": "Huángsè",
    "english-japanese": "ki",
    "arabic-english": "يلو"
  },
  "green": {
    "arabic": "أخضر",
    "chinese": "绿色",
    "english": "green",
    "japanese": "緑",
    "spanish": "verde",
    "english-arabic": "akhthar",
    "english-chinese": "Lǜsè",
    "english-japanese": "midori",
    "arabic-english": "جرين"
  },
  "blue": {
    "arabic": "أزرق",
    "chinese": "蓝色",
    "english": "blue",
    "japanese": "青",
    "spanish": "azul",
    "english-arabic": "azraq",
    "english-chinese": "Lán sè",
    "english-japanese": "ao",
    "arabic-english": "بلو"
  },
  "purple": {
    "arabic": "أرجواني",
    "chinese": "紫色",
    "english": "purple",
    "japanese": "紫",
    "spanish": "morado",
    "english-arabic": "arjwani",
    "english-chinese": "Zǐsè",
    "english-japanese": "murasaki",
    "arabic-english": "پرپل"
  }
}
